@startuml 软件

title 软件模块图

interface 通信模块{
    .. 通信模块的基类 ..
    与其他组件通信()
    数字传输异常()
    传输异常处理()
    工作状态异常处理模块()
    其他设备异常监控()
    异常状态传输模块()
    异常处理模块()
}

interface 功能测试模块{
    .. 功能测试模块的基类 ..
    功能测试_参数输出()
}

package "想定制作测试模块" {
    interface 编辑脚本{
        +读取xx导调()
        +新建xx导调()
        +编辑xx参数()
        +图形化xx参数()
    }
    class 雷达读取编辑
    class 目标编辑
    class 环境脚本编辑
    class 想定制作测试模块_通信模块
    通信模块 <|-- 想定制作测试模块_通信模块
    class 想定制作测试模块_功能测试模块
    功能测试模块 <|-- 想定制作测试模块_功能测试模块

    编辑脚本 <|-- 雷达读取编辑
    编辑脚本 <|-- 目标编辑
    编辑脚本 <|-- 环境脚本编辑
}

package "雷达工作状态维护模块" {
    class 雷达工作状态维护_通信模块
    通信模块 <|-- 雷达工作状态维护_通信模块
    class 雷达工作状态维护模块_功能测试模块
    功能测试模块 <|-- 雷达工作状态维护模块_功能测试模块

    class 状态现实控制{
        + 现实各个模块工作状态()
        + 控制内部允许七个模块()
    }
}
package "雷达天线仿真模块"{
    class 雷达天线仿真模块_通信模块
    通信模块 <|-- 雷达天线仿真模块_通信模块
    class 雷达天线仿真模块_功能测试模块
    功能测试模块 <|-- 雷达天线仿真模块_功能测试模块

    class 天线计算分析{
        +天线设计模块()
        +天线动态计算模块()
    }
}
package "时序仿真模块"{
    class 时序仿真模块_通信模块
    通信模块 <|-- 时序仿真模块_通信模块
    class 时序仿真模块_功能测试模块
    功能测试模块 <|-- 时序仿真模块_功能测试模块

    class 仿真时间推进模块{
        + 仿真时间计算控制模块()
    }
}
package "基带信号产生模块"{
    class 基带信号产生模块_通信模块
    通信模块 <|-- 基带信号产生模块_通信模块
    class 基带信号产生模块_功能测试模块
    功能测试模块 <|-- 基带信号产生模块_功能测试模块

    class 信号产生模块{
        噪声模型仿真模块()
        噪声生成模块()
        目标运动模型生成模块()
        单点目标生成模块()
        多点目标生成模块()
        海杂波生成模块()
        地面杂波生成模块()
        云雨杂波生成模块()
        无源箔条干扰信号模块()
        无源反射器干扰信号模块()
        吸收性无源干扰信号模块()
        有源噪声干扰信号模块()
        有源压制性干扰信号模块()
        多线程控制模块()
        信号合成模块()
    }
}

package "信号处理仿真模块"{
    class 信号处理仿真模块_通信模块
    通信模块 <|-- 信号处理仿真模块_通信模块
    class 信号处理仿真模块_功能测试模块
    功能测试模块 <|-- 信号处理仿真模块_功能测试模块

    class 信号处理模块{
        数字脉冲压缩模块()
        数字动目标参数测量模块()
        数字动目标显示模块()
        自适应动目标显示()
        背景噪声参数估计模块()
        背景噪声模型估计模块()
        恒虚警检测门限生成模块()
        动目标跟踪模块()
        动目标检测模块()
        超低旁瓣模块()
        旁瓣对消模块()
        自适应对消模块()
        旁瓣消隐模块()
        地面杂波检测模块()
        海杂波检测模块()
        云雨杂波检测模块()
        目标点迹信粗估计模块()
        目标点迹-点迹关联模块()
        目标点迹合并处理模块()
        数据关联模块()
        参数测量模块()
        数据打包模块()
    }
}

package "数据处理仿真模块"{
    class 数据处理仿真模块_通信模块
    通信模块 <|-- 数据处理仿真模块_通信模块
    class 数据处理仿真模块_功能测试模块
    功能测试模块 <|-- 数据处理仿真模块_功能测试模块

    class 数据处理模块{
        航迹起始建立模块()
        数据预处理模块()
        坐标变换模块()
        航迹实时产生模块()
        观测噪声压制模块()
        航迹-航迹关联模块()
        航迹-点迹关联模块()
        目标航迹确认模块()
        目标航迹滤波模块()
        数据关联模块()
        参数测量模块()
        影像文件提取()
        散射分析模块()
        杂波图建立模块()
        虚假航迹识别模块()
        航迹撤销模块()
        影像地理编码()
        数据格式转换()
        参数分析与统计模块()
        盲跟踪处理模块()
    }
}

package "雷达威力生成及上报模块"{
    class 雷达威力生成及上报模块_通信模块
    通信模块 <|-- 雷达威力生成及上报模块_通信模块
    class 雷达威力生成及上报模块_功能测试模块
    功能测试模块 <|-- 雷达威力生成及上报模块_功能测试模块

    class 雷达威力生成及上报模块_数据处理模块{
        雷达探测距离模块()
        图像预处理模块()
        区域提取模块()
        干扰距离计算模块()
        多路径效应计算模块()
        地形遮蔽区计算模块()
    }
}

package "姿态现实测试模块"{
    class 姿态现实测试模块_通信模块
    通信模块 <|-- 姿态现实测试模块_通信模块
    class 姿态现实测试模块_功能测试模块
    功能测试模块 <|-- 姿态现实测试模块_功能测试模块

    class 数据现实模块{
        频谱数据显示模块()
        形态学后处理显示模块()
        雷达威力显示模块()
        态势数据显示模块()
    }
}


@enduml

